artox_lab_sms:
    providers:
        sms_provider:
            infobip:
                token: '2493731bbe5a208deb4aeb7b658b4d3f-43af8353-b209-4f14-87e6-157f7c4b03e2'
                sender: 'Alwarda.sa'
        # You must to define at least one provider configuration
        # See more info at https://github.com/artox-lab/sms-bundle
