vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: '/images/products'
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer:
                service: vich_uploader.namer_uniqid
        order_images:
            uri_prefix: '/images/orders'
            upload_destination: '%kernel.project_dir%/public/images/orders'
            namer:
                service: vich_uploader.namer_uniqid
        categories_icons:
            uri_prefix: '/images/categories'
            upload_destination: '%kernel.project_dir%/public/images/categories'
            namer:
                service: vich_uploader.namer_uniqid
        client_files:
            uri_prefix: '/client_files'
            upload_destination: '%kernel.project_dir%/public/client_files'
            namer:
                service: vich_uploader.namer_uniqid
        blog_images:
            uri_prefix: '/blog_images'
            upload_destination: '%kernel.project_dir%/public/blog_images'
            namer:
                service: vich_uploader.namer_uniqid
