#controllers:
#    resource: ../../src/Controller/
#    type: annotation

front_end:
    resource: ../../src/Controller/Front/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: en|ar
    defaults:
        _locale: en

dashboard:
    resource: ../../src/Controller/Dashboard/
    type: annotation
    prefix: /panel

api_controllers:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api

kernel:
    resource: ../../src/Kernel.php
    type: annotation
